// skill-tree-defs.js
// Auto-generated by scripts/apply-skill-editor-export.mjs.
// Note: this generator rewrites the file and removes manual comments.

export const skillProgressionDefs = {
  defaultStartingSkillPoints: 6,
  startingSkillPointsByPawnDefId: {
    default: 6
  },
  defaultUnlockedRecipes: [
    "roastBarley",
    "craftProphecyPopulationScroll",
    "craftAlmanacGrainScroll",
    "craftRecordFoodScroll",
    "craftHistorySystemsScroll",
    "craftScriptureSystemsScroll"
  ],
  defaultUnlockedHubStructures: [
    "granary",
    "ritualShrine",
    "storehouse"
  ]
};

export const skillTrees = {
  systemColorMap: {
    id: "systemColorMap",
    name: "System Color Map",
    startNodeId: "Memory",
    ui: {
      accentColor: 16777215,
      layoutMode: "ringByTags",
      nodeSizes: {
        defaultRadius: 12,
        notableRadius: 24
      },
      ringLayout: {
        ringOrder: [
          "core",
          "ring_01",
          "ring_02",
          "ring_03",
          "ring_04",
          "ring_05",
          "ring_06",
          "ring_07",
          "ring_08",
          "ring_09",
          "early",
          "mid",
          "late"
        ],
        radii: {
          core: 0,
          ring_01: 300,
          ring_02: 500,
          ring_03: 800,
          early: 500,
          ring_04: 1000,
          ring_05: 1200,
          ring_06: 1500,
          mid: 900,
          ring_07: 1600,
          ring_08: 1700,
          ring_09: 1800,
          late: 1200
        },
        wedgeSpansDeg: {
          Blue: 50,
          Green: 50,
          Red: 50,
          Black: 50,
          BlueGreen: 25,
          GreenRed: 25,
          RedBlack: 25,
          BlackBlue: 25
        },
        barycenterIterations: 32,
        localSwapIterations: 32,
        overlapIterations: 32,
        overlapPaddingPx: 16,
        componentBandGapDeg: 16,
        angleSwapTeleportWeight: 4,
        radialNudgeIterations: 64,
        radialNudgeMaxPx: 248,
        radialNudgePaddingPx: 64,
        radialNudgeSpring: 8,
        coreSpread: 16
      }
    }
  }
};

export const skillNodes = {
  Astronomy: {
    id: "Astronomy",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "Papyrus_01",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlueEarly_01",
      "BlueEarly_03",
      "Cooking",
      "Crafting"
    ],
    uiPos: {
      x: 628,
      y: 619
    },
    onUnlock: []
  },
  Basket: {
    id: "Basket",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "GreenEarly_Notable_01",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Notable"
    ],
    adjacent: [
      "Cooking",
      "Forage",
      "GreenEarly_01",
      "GreenEarly_03"
    ],
    uiPos: {
      x: 825,
      y: 619
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "recipe",
        recipeId: "weaveBasket"
      }
    ]
  },
  Beer: {
    id: "Beer",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "GreenEarly_Notable_04",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Notable"
    ],
    adjacent: [
      "BlueGreenEarly_08",
      "GreenEarly_12"
    ],
    uiPos: {
      x: 1057,
      y: 1469
    },
    onUnlock: []
  },
  BlackBlueEarly_01: {
    id: "BlackBlueEarly_01",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "BlackBlueEarly_01",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early",
      "Hybrid"
    ],
    adjacent: [
      "BlackBlueEarly_03",
      "Papyrus"
    ],
    uiPos: {
      x: 226,
      y: 638
    },
    onUnlock: []
  },
  BlackBlueEarly_02: {
    id: "BlackBlueEarly_02",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "BlackBlueEarly_02",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early",
      "Hybrid"
    ],
    adjacent: [
      "BlackBlueEarly_03",
      "BlackEarly_Notable"
    ],
    uiPos: {
      x: 226,
      y: 421
    },
    onUnlock: []
  },
  BlackBlueEarly_03: {
    id: "BlackBlueEarly_03",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlackBlueEarly_03",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early",
      "Hybrid"
    ],
    adjacent: [
      "BlackBlueEarly_01",
      "BlackBlueEarly_02",
      "BlackBlueEarly_Notable"
    ],
    uiPos: {
      x: -85,
      y: 530
    },
    onUnlock: []
  },
  BlackBlueEarly_04: {
    id: "BlackBlueEarly_04",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlackBlueEarly_04",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early",
      "Hybrid"
    ],
    adjacent: [
      "BlackBlueEarly_Notable",
      "BlueBlackEarly_05"
    ],
    uiPos: {
      x: -485,
      y: 529
    },
    onUnlock: []
  },
  BlackBlueEarly_Notable: {
    id: "BlackBlueEarly_Notable",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlackBlueEarly_Notable_02",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early",
      "Hybrid",
      "Notable"
    ],
    adjacent: [
      "BlackBlueEarly_03",
      "BlackBlueEarly_04",
      "BlueBlackEarly_06",
      "BlueBlackEarly_08"
    ],
    uiPos: {
      x: -285,
      y: 529
    },
    onUnlock: []
  },
  BlackBlueMid_Notable: {
    id: "BlackBlueMid_Notable",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "BlackBlueMidNotable_01",
    desc: "Bridge anchor (immediate domain).",
    cost: 2,
    tags: [
      "Black",
      "Blue",
      "Hybrid",
      "Mid",
      "Notable"
    ],
    adjacent: [
      "BlackMid_04",
      "BlueBlackEarly_05",
      "BlueMid_06"
    ],
    uiPos: {
      x: -885,
      y: 523
    },
    onUnlock: []
  },
  BlackEarly_01: {
    id: "BlackEarly_01",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "BlackNodeEarly_01",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_02",
      "BlackEarly_Notable",
      "Weaving"
    ],
    uiPos: {
      x: 443,
      y: 405
    },
    onUnlock: []
  },
  BlackEarly_02: {
    id: "BlackEarly_02",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "BlackNodeEarly_02",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_01",
      "Worship"
    ],
    uiPos: {
      x: 473,
      y: 350
    },
    onUnlock: []
  },
  BlackEarly_03: {
    id: "BlackEarly_03",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "BlackNodeEarly_03",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_04",
      "Worship"
    ],
    uiPos: {
      x: 573,
      y: 265
    },
    onUnlock: []
  },
  BlackEarly_04: {
    id: "BlackEarly_04",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "BlackNodeEarly_04",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_03",
      "BlackEarly_Notable"
    ],
    uiPos: {
      x: 539,
      y: 286
    },
    onUnlock: []
  },
  BlackEarly_05: {
    id: "BlackEarly_05",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlackNodeEarly_05",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_06",
      "BlackEarly_Notable"
    ],
    uiPos: {
      x: 66,
      y: 61
    },
    onUnlock: []
  },
  BlackEarly_06: {
    id: "BlackEarly_06",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlackNodeEarly_06",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_05",
      "BlackEarly_Notable_02"
    ],
    uiPos: {
      x: 44,
      y: 94
    },
    onUnlock: []
  },
  BlackEarly_07: {
    id: "BlackEarly_07",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlackNodeEarly_07",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_08",
      "BlackEarly_Notable"
    ],
    uiPos: {
      x: 279,
      y: -141
    },
    onUnlock: []
  },
  BlackEarly_08: {
    id: "BlackEarly_08",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlackNodeEarly_08",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_07",
      "BlackEarly_Notable_02"
    ],
    uiPos: {
      x: 246,
      y: -119
    },
    onUnlock: []
  },
  BlackEarly_09: {
    id: "BlackEarly_09",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlackEarly_09",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_10",
      "BlackEarly_Notable_02"
    ],
    uiPos: {
      x: 4,
      y: -438
    },
    onUnlock: []
  },
  BlackEarly_10: {
    id: "BlackEarly_10",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlackEarly_10",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_09",
      "BlackEarly_Notable_03"
    ],
    uiPos: {
      x: 174,
      y: -542
    },
    onUnlock: []
  },
  BlackEarly_11: {
    id: "BlackEarly_11",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "BlackEarly_11",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_12",
      "BlackEarly_Notable_02"
    ],
    uiPos: {
      x: -540,
      y: -292
    },
    onUnlock: []
  },
  BlackEarly_12: {
    id: "BlackEarly_12",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlackEarly_12",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early"
    ],
    adjacent: [
      "BlackEarly_11",
      "BlackEarly_Notable_04"
    ],
    uiPos: {
      x: -366,
      y: 7
    },
    onUnlock: []
  },
  BlackEarly_Notable: {
    id: "BlackEarly_Notable",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "BlackNodeEarlyNotable_01",
    desc: "Cluster punctuation.",
    cost: 2,
    tags: [
      "Black",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlackBlueEarly_02",
      "BlackEarly_01",
      "BlackEarly_04",
      "BlackEarly_05",
      "BlackEarly_07",
      "RedBlackEarly_01"
    ],
    uiPos: {
      x: 360,
      y: 177
    },
    onUnlock: []
  },
  BlackEarly_Notable_02: {
    id: "BlackEarly_Notable_02",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlackEarly_Notable_02",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlackEarly_06",
      "BlackEarly_08",
      "BlackEarly_09",
      "BlackEarly_11",
      "BlackMid_01"
    ],
    uiPos: {
      x: 8,
      y: -178
    },
    onUnlock: []
  },
  BlackEarly_Notable_03: {
    id: "BlackEarly_Notable_03",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlackEarly_Notable_03",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlackEarly_10",
      "RedBlackEarly_09"
    ],
    uiPos: {
      x: 372,
      y: -410
    },
    onUnlock: []
  },
  BlackEarly_Notable_04: {
    id: "BlackEarly_Notable_04",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlackEarly_Notable_04",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlackEarly_12",
      "BlueBlackEarly_09"
    ],
    uiPos: {
      x: -225,
      y: 186
    },
    onUnlock: []
  },
  BlackLate_01: {
    id: "BlackLate_01",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlackNodeLate_01",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Black",
      "Late"
    ],
    adjacent: [
      "BlackLate_02",
      "BlackMid_Notable"
    ],
    uiPos: {
      x: -733,
      y: -541
    },
    onUnlock: []
  },
  BlackLate_02: {
    id: "BlackLate_02",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlackNodeLate_02",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Black",
      "Late"
    ],
    adjacent: [
      "BlackLate_01",
      "BlackLate_03"
    ],
    uiPos: {
      x: -709,
      y: -573
    },
    onUnlock: []
  },
  BlackLate_03: {
    id: "BlackLate_03",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlackNodeLate_03",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Black",
      "Late"
    ],
    adjacent: [
      "BlackLate_02",
      "BlackLate_Notable"
    ],
    uiPos: {
      x: -684,
      y: -604
    },
    onUnlock: []
  },
  BlackLate_Notable: {
    id: "BlackLate_Notable",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlackNodeLateNotable_01",
    desc: "Outer edge anchor.",
    cost: 4,
    tags: [
      "Black",
      "Late",
      "Notable"
    ],
    adjacent: [
      "BlackLate_03"
    ],
    uiPos: {
      x: -651,
      y: -644
    },
    onUnlock: []
  },
  BlackMid_01: {
    id: "BlackMid_01",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "BlackNodeMid_01",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Black",
      "Mid"
    ],
    adjacent: [
      "BlackEarly_Notable_02",
      "BlackMid_02"
    ],
    uiPos: {
      x: -126,
      y: -713
    },
    onUnlock: []
  },
  BlackMid_02: {
    id: "BlackMid_02",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "BlackNodeMid_02",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Black",
      "Mid"
    ],
    adjacent: [
      "BlackMid_01",
      "BlackMid_Notable"
    ],
    uiPos: {
      x: -130,
      y: -830
    },
    onUnlock: []
  },
  BlackMid_03: {
    id: "BlackMid_03",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "BlackNodeMid_03",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Black",
      "Mid"
    ],
    adjacent: [
      "BlackMid_04",
      "BlackMid_Notable"
    ],
    uiPos: {
      x: -695,
      y: -421
    },
    onUnlock: []
  },
  BlackMid_04: {
    id: "BlackMid_04",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "BlackNodeMid_04",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Black",
      "Mid"
    ],
    adjacent: [
      "BlackBlueMid_Notable",
      "BlackMid_03"
    ],
    uiPos: {
      x: -789,
      y: -18
    },
    onUnlock: []
  },
  BlackMid_05: {
    id: "BlackMid_05",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlackNodeMid_05",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Black",
      "Mid"
    ],
    adjacent: [
      "BlackMid_06",
      "BlackMid_Notable"
    ],
    uiPos: {
      x: -59,
      y: -1096
    },
    onUnlock: []
  },
  BlackMid_06: {
    id: "BlackMid_06",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "BlackNodeMid_06",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Black",
      "Mid"
    ],
    adjacent: [
      "BlackMid_05",
      "RedBlackMid_Notable"
    ],
    uiPos: {
      x: 133,
      y: -1068
    },
    onUnlock: []
  },
  BlackMid_Notable: {
    id: "BlackMid_Notable",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "BlackNodeMidNotable_01",
    desc: "Mid anchor.",
    cost: 2,
    tags: [
      "Black",
      "Mid",
      "Notable"
    ],
    adjacent: [
      "BlackLate_01",
      "BlackMid_02",
      "BlackMid_03",
      "BlackMid_05"
    ],
    uiPos: {
      x: -296,
      y: -711
    },
    onUnlock: []
  },
  BlueBlackEarly_05: {
    id: "BlueBlackEarly_05",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "BlueBlackEarly_05",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlackBlueEarly_04",
      "BlackBlueMid_Notable"
    ],
    uiPos: {
      x: -785,
      y: 526
    },
    onUnlock: []
  },
  BlueBlackEarly_06: {
    id: "BlueBlackEarly_06",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlueBlackEarly_06",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlackBlueEarly_Notable",
      "BlueBlackEarly_07"
    ],
    uiPos: {
      x: -470,
      y: 721
    },
    onUnlock: []
  },
  BlueBlackEarly_07: {
    id: "BlueBlackEarly_07",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueBlackEarly_07",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueBlackEarly_06",
      "BlueEarlyNotable_04"
    ],
    uiPos: {
      x: -262,
      y: 746
    },
    onUnlock: []
  },
  BlueBlackEarly_08: {
    id: "BlueBlackEarly_08",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlueBlackEarly_08",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlackBlueEarly_Notable",
      "BlueBlackEarly_09"
    ],
    uiPos: {
      x: -470,
      y: 338
    },
    onUnlock: []
  },
  BlueBlackEarly_09: {
    id: "BlueBlackEarly_09",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueBlackEarly_09",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlackEarly_Notable_04",
      "BlueBlackEarly_08"
    ],
    uiPos: {
      x: -262,
      y: 313
    },
    onUnlock: []
  },
  BlueEarly_01: {
    id: "BlueEarly_01",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "BlueNodeEarly_01",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "Astronomy",
      "BlueEarly_02",
      "Farming"
    ],
    uiPos: {
      x: 611,
      y: 795
    },
    onUnlock: []
  },
  BlueEarly_02: {
    id: "BlueEarly_02",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "BlueNodeEarly_02",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_01",
      "Papyrus"
    ],
    uiPos: {
      x: 520,
      y: 792
    },
    onUnlock: []
  },
  BlueEarly_03: {
    id: "BlueEarly_03",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "BlueNodeEarly_03",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "Astronomy",
      "BlueEarly_04"
    ],
    uiPos: {
      x: 480,
      y: 684
    },
    onUnlock: []
  },
  BlueEarly_04: {
    id: "BlueEarly_04",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "BlueNodeEarly_04",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_03",
      "Papyrus",
      "Weaving"
    ],
    uiPos: {
      x: 437,
      y: 634
    },
    onUnlock: []
  },
  BlueEarly_05: {
    id: "BlueEarly_05",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlueNodeEarly_05",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_06",
      "Papyrus"
    ],
    uiPos: {
      x: 246,
      y: 1178
    },
    onUnlock: []
  },
  BlueEarly_06: {
    id: "BlueEarly_06",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlueNodeEarly_06",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_05",
      "Prophecy"
    ],
    uiPos: {
      x: 279,
      y: 1200
    },
    onUnlock: []
  },
  BlueEarly_07: {
    id: "BlueEarly_07",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlueNodeEarly_07",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_08",
      "Prophecy"
    ],
    uiPos: {
      x: 66,
      y: 998
    },
    onUnlock: []
  },
  BlueEarly_08: {
    id: "BlueEarly_08",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlueNodeEarly_08",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_07",
      "Papyrus"
    ],
    uiPos: {
      x: 44,
      y: 965
    },
    onUnlock: []
  },
  BlueEarly_09: {
    id: "BlueEarly_09",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlueEarly_09",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_10",
      "Prophecy"
    ],
    uiPos: {
      x: 176,
      y: 1602
    },
    onUnlock: []
  },
  BlueEarly_10: {
    id: "BlueEarly_10",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueEarly_10",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_09",
      "BlueEarlyNotable_03"
    ],
    uiPos: {
      x: 245,
      y: 1412
    },
    onUnlock: []
  },
  BlueEarly_11: {
    id: "BlueEarly_11",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueEarly_11",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_12",
      "Prophecy"
    ],
    uiPos: {
      x: -63,
      y: 1159
    },
    onUnlock: []
  },
  BlueEarly_12: {
    id: "BlueEarly_12",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlueEarly_12",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early"
    ],
    adjacent: [
      "BlueEarly_11",
      "BlueEarlyNotable_04"
    ],
    uiPos: {
      x: -358,
      y: 1068
    },
    onUnlock: []
  },
  BlueEarlyNotable_03: {
    id: "BlueEarlyNotable_03",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueEarlyNotable_03",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlueEarly_10",
      "BlueGreenEarly_07"
    ],
    uiPos: {
      x: 370,
      y: 1468
    },
    onUnlock: []
  },
  BlueEarlyNotable_04: {
    id: "BlueEarlyNotable_04",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueEarlyNotable_04",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlueBlackEarly_07",
      "BlueEarly_12"
    ],
    uiPos: {
      x: -225,
      y: 872
    },
    onUnlock: []
  },
  BlueGreenEarly_01: {
    id: "BlueGreenEarly_01",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_01",
    desc: "Hybrid bridge.",
    cost: 2,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid"
    ],
    adjacent: [
      "BlueGreenEarly_03",
      "Papyrus"
    ],
    uiPos: {
      x: 649,
      y: 1025
    },
    onUnlock: []
  },
  BlueGreenEarly_02: {
    id: "BlueGreenEarly_02",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_02",
    desc: "Hybrid bridge.",
    cost: 2,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid"
    ],
    adjacent: [
      "BlueGreenEarly_03",
      "Storehouse"
    ],
    uiPos: {
      x: 780,
      y: 1025
    },
    onUnlock: []
  },
  BlueGreenEarly_03: {
    id: "BlueGreenEarly_03",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_03",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid"
    ],
    adjacent: [
      "BlueGreenEarly_01",
      "BlueGreenEarly_02",
      "BlueGreenEarly_Notable"
    ],
    uiPos: {
      x: 715,
      y: 1329
    },
    onUnlock: []
  },
  BlueGreenEarly_04: {
    id: "BlueGreenEarly_04",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_04",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid"
    ],
    adjacent: [
      "BlueGreenEarly_05",
      "BlueGreenEarly_Notable"
    ],
    uiPos: {
      x: 715,
      y: 1729
    },
    onUnlock: []
  },
  BlueGreenEarly_05: {
    id: "BlueGreenEarly_05",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_05",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Green"
    ],
    adjacent: [
      "BlueGreenEarly_04",
      "BlueGreenMid_Notable"
    ],
    uiPos: {
      x: 715,
      y: 2030
    },
    onUnlock: []
  },
  BlueGreenEarly_06: {
    id: "BlueGreenEarly_06",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_06",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid"
    ],
    adjacent: [
      "BlueGreenEarly_07",
      "BlueGreenEarly_Notable"
    ],
    uiPos: {
      x: 577,
      y: 1520
    },
    onUnlock: []
  },
  BlueGreenEarly_07: {
    id: "BlueGreenEarly_07",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_07",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid"
    ],
    adjacent: [
      "BlueEarlyNotable_03",
      "BlueGreenEarly_06"
    ],
    uiPos: {
      x: 455,
      y: 1701
    },
    onUnlock: []
  },
  BlueGreenEarly_08: {
    id: "BlueGreenEarly_08",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_08",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid"
    ],
    adjacent: [
      "Beer",
      "BlueGreenEarly_09"
    ],
    uiPos: {
      x: 974,
      y: 1701
    },
    onUnlock: []
  },
  BlueGreenEarly_09: {
    id: "BlueGreenEarly_09",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_09",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid"
    ],
    adjacent: [
      "BlueGreenEarly_08",
      "BlueGreenEarly_Notable"
    ],
    uiPos: {
      x: 852,
      y: 1520
    },
    onUnlock: []
  },
  BlueGreenEarly_Notable: {
    id: "BlueGreenEarly_Notable",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_Notable",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid",
      "Notable"
    ],
    adjacent: [
      "BlueGreenEarly_03",
      "BlueGreenEarly_04",
      "BlueGreenEarly_06",
      "BlueGreenEarly_09"
    ],
    uiPos: {
      x: 715,
      y: 1529
    },
    onUnlock: []
  },
  BlueGreenMid_Notable: {
    id: "BlueGreenMid_Notable",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "BlueGreenMidNotable_01",
    desc: "Bridge anchor (deferred domain).",
    cost: 2,
    tags: [
      "Blue",
      "Green",
      "Hybrid",
      "Mid",
      "Notable"
    ],
    adjacent: [
      "BlueGreenEarly_05",
      "BlueMid_04",
      "GreenMid_04"
    ],
    uiPos: {
      x: 715,
      y: 2130
    },
    onUnlock: []
  },
  BlueLate_01: {
    id: "BlueLate_01",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlueNodeLate_01",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Blue",
      "Late"
    ],
    adjacent: [
      "BlueLate_02",
      "BlueMid_Notable"
    ],
    uiPos: {
      x: -365,
      y: 1970
    },
    onUnlock: []
  },
  BlueLate_02: {
    id: "BlueLate_02",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlueNodeLate_02",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Blue",
      "Late"
    ],
    adjacent: [
      "BlueLate_01",
      "BlueLate_03"
    ],
    uiPos: {
      x: -460,
      y: 1893
    },
    onUnlock: []
  },
  BlueLate_03: {
    id: "BlueLate_03",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlueNodeLate_03",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Blue",
      "Late"
    ],
    adjacent: [
      "BlueLate_02",
      "BlueLate_Notable"
    ],
    uiPos: {
      x: -667,
      y: 1683
    },
    onUnlock: []
  },
  BlueLate_Notable: {
    id: "BlueLate_Notable",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "BlueNodeLateNotable_01",
    desc: "Outer edge anchor.",
    cost: 4,
    tags: [
      "Blue",
      "Late",
      "Notable"
    ],
    adjacent: [
      "BlueLate_03"
    ],
    uiPos: {
      x: -761,
      y: 1560
    },
    onUnlock: []
  },
  BlueMid_01: {
    id: "BlueMid_01",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "BlueNodeMid_01",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Blue",
      "Mid"
    ],
    adjacent: [
      "BlueMid_02",
      "Prophecy"
    ],
    uiPos: {
      x: -83,
      y: 1426
    },
    onUnlock: []
  },
  BlueMid_02: {
    id: "BlueMid_02",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "BlueNodeMid_02",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Blue",
      "Mid"
    ],
    adjacent: [
      "BlueMid_01",
      "BlueMid_Notable"
    ],
    uiPos: {
      x: -183,
      y: 1731
    },
    onUnlock: []
  },
  BlueMid_03: {
    id: "BlueMid_03",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "BlueNodeMid_03",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Blue",
      "Mid"
    ],
    adjacent: [
      "BlueMid_04",
      "BlueMid_Notable"
    ],
    uiPos: {
      x: -178,
      y: 1976
    },
    onUnlock: []
  },
  BlueMid_04: {
    id: "BlueMid_04",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "BlueNodeMid_04",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Blue",
      "Mid"
    ],
    adjacent: [
      "BlueGreenMid_Notable",
      "BlueMid_03"
    ],
    uiPos: {
      x: 133,
      y: 2127
    },
    onUnlock: []
  },
  BlueMid_05: {
    id: "BlueMid_05",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "BlueNodeMid_05",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Blue",
      "Mid"
    ],
    adjacent: [
      "BlueMid_06",
      "BlueMid_Notable"
    ],
    uiPos: {
      x: -697,
      y: 1478
    },
    onUnlock: []
  },
  BlueMid_06: {
    id: "BlueMid_06",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "BlueNodeMid_06",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Blue",
      "Mid"
    ],
    adjacent: [
      "BlackBlueMid_Notable",
      "BlueMid_05"
    ],
    uiPos: {
      x: -883,
      y: 1111
    },
    onUnlock: []
  },
  BlueMid_Notable: {
    id: "BlueMid_Notable",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "BlueNodeMidNotable_01",
    desc: "Mid anchor.",
    cost: 2,
    tags: [
      "Blue",
      "Mid",
      "Notable"
    ],
    adjacent: [
      "BlueLate_01",
      "BlueMid_02",
      "BlueMid_03",
      "BlueMid_05"
    ],
    uiPos: {
      x: -336,
      y: 1736
    },
    onUnlock: []
  },
  Cooking: {
    id: "Cooking",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "GreenEarly_Notable_01",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Notable"
    ],
    adjacent: [
      "Astronomy",
      "Basket",
      "Hearth"
    ],
    uiPos: {
      x: 732,
      y: 724
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "hub",
        tagId: "canCook"
      },
      {
        op: "GrantUnlock",
        unlockType: "recipe",
        recipeId: "roastBarley"
      },
      {
        op: "GrantUnlock",
        unlockType: "recipe",
        recipeId: "roastSmallFish"
      },
      {
        op: "GrantUnlock",
        unlockType: "recipe",
        recipeId: "roastMediumFish"
      },
      {
        op: "GrantUnlock",
        unlockType: "recipe",
        recipeId: "roastLargeFish"
      }
    ]
  },
  Crafting: {
    id: "Crafting",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlackBlueEarly_Notable_01",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Blue",
      "Early",
      "Hybrid",
      "Notable"
    ],
    adjacent: [
      "Astronomy",
      "Worship"
    ],
    uiPos: {
      x: 483,
      y: 528
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "hub",
        tagId: "canCraft"
      }
    ]
  },
  Distribute: {
    id: "Distribute",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "RedNodeEarlyNotable_01",
    desc: "Cluster punctuation.",
    cost: 2,
    tags: [
      "Early",
      "Notable",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_01",
      "RedBlackEarly_02",
      "RedEarly_02",
      "RedEarly_04",
      "RedEarly_05",
      "RedEarly_07"
    ],
    uiPos: {
      x: 1118,
      y: 232
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "hub",
        tagId: "distributor"
      }
    ]
  },
  Farming: {
    id: "Farming",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueGreenEarly_Notable_01",
    desc: "",
    cost: 2,
    tags: [
      "Blue",
      "Early",
      "Green",
      "Hybrid",
      "Notable"
    ],
    adjacent: [
      "BlueEarly_01",
      "GreenEarly_04"
    ],
    uiPos: {
      x: 718,
      y: 902
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "env",
        tagId: "farmable"
      }
    ]
  },
  Fish: {
    id: "Fish",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "RedEarly_Notable_01",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Notable",
      "Red"
    ],
    adjacent: [
      "Forage",
      "Housing",
      "RedEarly_01",
      "RedEarly_03"
    ],
    uiPos: {
      x: 823,
      y: 452
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "env",
        tagId: "fishable"
      }
    ]
  },
  Forage: {
    id: "Forage",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "RedEarly_Notable_01",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Notable",
      "Red"
    ],
    adjacent: [
      "Basket",
      "Fish",
      "Hearth"
    ],
    uiPos: {
      x: 961,
      y: 543
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "env",
        tagId: "forageable"
      }
    ]
  },
  GreenEarly_01: {
    id: "GreenEarly_01",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "GreenNodeEarly_01",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "Basket",
      "GreenEarly_02"
    ],
    uiPos: {
      x: 988,
      y: 649
    },
    onUnlock: []
  },
  GreenEarly_02: {
    id: "GreenEarly_02",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "GreenNodeEarly_02",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "GreenEarly_01",
      "Storehouse"
    ],
    uiPos: {
      x: 956,
      y: 709
    },
    onUnlock: []
  },
  GreenEarly_03: {
    id: "GreenEarly_03",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "GreenNodeEarly_03",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "Basket",
      "GreenEarly_04"
    ],
    uiPos: {
      x: 905,
      y: 806
    },
    onUnlock: []
  },
  GreenEarly_04: {
    id: "GreenEarly_04",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "GreenNodeEarly_04",
    desc: "Early ring.",
    cost: 2,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "Farming",
      "GreenEarly_03",
      "Storehouse"
    ],
    uiPos: {
      x: 815,
      y: 803
    },
    onUnlock: []
  },
  GreenEarly_05: {
    id: "GreenEarly_05",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "GreenNodeEarly_05",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "GreenEarly_06",
      "Storehouse"
    ],
    uiPos: {
      x: 1363,
      y: 998
    },
    onUnlock: []
  },
  GreenEarly_06: {
    id: "GreenEarly_06",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "GreenNodeEarly_06",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "GreenEarly_05",
      "Preserve"
    ],
    uiPos: {
      x: 1466,
      y: 803
    },
    onUnlock: []
  },
  GreenEarly_07: {
    id: "GreenEarly_07",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "GreenNodeEarly_07",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "GreenEarly_08",
      "Storehouse"
    ],
    uiPos: {
      x: 988,
      y: 1281
    },
    onUnlock: []
  },
  GreenEarly_08: {
    id: "GreenEarly_08",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "GreenNodeEarly_08",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "GreenEarly_07",
      "Preserve"
    ],
    uiPos: {
      x: 1183,
      y: 1178
    },
    onUnlock: []
  },
  GreenEarly_09: {
    id: "GreenEarly_09",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "GreenEarly_09",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "GreenEarly_10",
      "Preserve"
    ],
    uiPos: {
      x: 1754,
      y: 1130
    },
    onUnlock: []
  },
  GreenEarly_10: {
    id: "GreenEarly_10",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "GreenEarly_10",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "GreenEarly_09",
      "GreenEarly_Notable_03"
    ],
    uiPos: {
      x: 1842,
      y: 940
    },
    onUnlock: []
  },
  GreenEarly_11: {
    id: "GreenEarly_11",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "GreenEarly_11",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "GreenEarly_12",
      "Preserve"
    ],
    uiPos: {
      x: 1533,
      y: 1786
    },
    onUnlock: []
  },
  GreenEarly_12: {
    id: "GreenEarly_12",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "GreenEarly_12",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green"
    ],
    adjacent: [
      "Beer",
      "GreenEarly_11"
    ],
    uiPos: {
      x: 1220,
      y: 1618
    },
    onUnlock: []
  },
  GreenEarly_Notable_03: {
    id: "GreenEarly_Notable_03",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "GreenEarly_Notable_03",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Notable"
    ],
    adjacent: [
      "GreenEarly_10",
      "GreenRedEarly_07"
    ],
    uiPos: {
      x: 1654,
      y: 872
    },
    onUnlock: []
  },
  GreenLate_01: {
    id: "GreenLate_01",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "GreenNodeLate_01",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Green",
      "Late"
    ],
    adjacent: [
      "GreenLate_02",
      "GreenMid_Notable"
    ],
    uiPos: {
      x: 2166,
      y: 1594
    },
    onUnlock: []
  },
  GreenLate_02: {
    id: "GreenLate_02",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "GreenNodeLate_02",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Green",
      "Late"
    ],
    adjacent: [
      "GreenLate_01",
      "GreenLate_03"
    ],
    uiPos: {
      x: 2081,
      y: 1702
    },
    onUnlock: []
  },
  GreenLate_03: {
    id: "GreenLate_03",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "GreenNodeLate_03",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Green",
      "Late"
    ],
    adjacent: [
      "GreenLate_02",
      "GreenLate_Notable"
    ],
    uiPos: {
      x: 1868,
      y: 1911
    },
    onUnlock: []
  },
  GreenLate_Notable: {
    id: "GreenLate_Notable",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "GreenNodeLateNotable_01",
    desc: "Outer edge anchor.",
    cost: 4,
    tags: [
      "Green",
      "Late",
      "Notable"
    ],
    adjacent: [
      "GreenLate_03"
    ],
    uiPos: {
      x: 1745,
      y: 2005
    },
    onUnlock: []
  },
  GreenMid_01: {
    id: "GreenMid_01",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "GreenNodeMid_01",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Green",
      "Mid"
    ],
    adjacent: [
      "GreenMid_02",
      "Preserve"
    ],
    uiPos: {
      x: 1754,
      y: 1130
    },
    onUnlock: []
  },
  GreenMid_02: {
    id: "GreenMid_02",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "GreenNodeMid_02",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Green",
      "Mid"
    ],
    adjacent: [
      "GreenMid_01",
      "GreenMid_Notable"
    ],
    uiPos: {
      x: 1947,
      y: 1385
    },
    onUnlock: []
  },
  GreenMid_03: {
    id: "GreenMid_03",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "GreenNodeMid_03",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Green",
      "Mid"
    ],
    adjacent: [
      "GreenMid_04",
      "GreenMid_Notable"
    ],
    uiPos: {
      x: 1665,
      y: 1939
    },
    onUnlock: []
  },
  GreenMid_04: {
    id: "GreenMid_04",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "GreenNodeMid_04",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Green",
      "Mid"
    ],
    adjacent: [
      "BlueGreenMid_Notable",
      "GreenMid_03"
    ],
    uiPos: {
      x: 1296,
      y: 2127
    },
    onUnlock: []
  },
  GreenMid_05: {
    id: "GreenMid_05",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "GreenNodeMid_05",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Green",
      "Mid"
    ],
    adjacent: [
      "GreenMid_06",
      "GreenMid_Notable"
    ],
    uiPos: {
      x: 2170,
      y: 1408
    },
    onUnlock: []
  },
  GreenMid_06: {
    id: "GreenMid_06",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "GreenNodeMid_06",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Green",
      "Mid"
    ],
    adjacent: [
      "GreenMid_05",
      "GreenRedMid_Notable"
    ],
    uiPos: {
      x: 2312,
      y: 1111
    },
    onUnlock: []
  },
  GreenMid_Notable: {
    id: "GreenMid_Notable",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "GreenNodeMidNotable_01",
    desc: "Mid anchor.",
    cost: 2,
    tags: [
      "Green",
      "Mid",
      "Notable"
    ],
    adjacent: [
      "GreenLate_01",
      "GreenMid_02",
      "GreenMid_03",
      "GreenMid_05"
    ],
    uiPos: {
      x: 1947,
      y: 1550
    },
    onUnlock: []
  },
  GreenRedEarly_01: {
    id: "GreenRedEarly_01",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "GreenRedEarly_01",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Hybrid",
      "Red"
    ],
    adjacent: [
      "Distribute",
      "GreenRedEarly_03"
    ],
    uiPos: {
      x: 1203,
      y: 421
    },
    onUnlock: []
  },
  GreenRedEarly_02: {
    id: "GreenRedEarly_02",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "GreenRedEarly_02",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Hybrid",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_03",
      "Storehouse"
    ],
    uiPos: {
      x: 1203,
      y: 638
    },
    onUnlock: []
  },
  GreenRedEarly_03: {
    id: "GreenRedEarly_03",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "GreenRedEarly_03",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Hybrid",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_01",
      "GreenRedEarly_02",
      "GreenRedEarly_Notable"
    ],
    uiPos: {
      x: 1514,
      y: 531
    },
    onUnlock: []
  },
  GreenRedEarly_04: {
    id: "GreenRedEarly_04",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "GreenRedEarly_04",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Hybrid",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_05",
      "GreenRedEarly_Notable"
    ],
    uiPos: {
      x: 1914,
      y: 530
    },
    onUnlock: []
  },
  GreenRedEarly_05: {
    id: "GreenRedEarly_05",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "GreenRedEarly_05",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_04",
      "GreenRedMid_Notable"
    ],
    uiPos: {
      x: 2215,
      y: 530
    },
    onUnlock: []
  },
  GreenRedEarly_06: {
    id: "GreenRedEarly_06",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "GreenRedEarly_06",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_07",
      "GreenRedEarly_Notable"
    ],
    uiPos: {
      x: 1705,
      y: 667
    },
    onUnlock: []
  },
  GreenRedEarly_07: {
    id: "GreenRedEarly_07",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "GreenRedEarly_07",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Red"
    ],
    adjacent: [
      "GreenEarly_Notable_03",
      "GreenRedEarly_06"
    ],
    uiPos: {
      x: 1886,
      y: 789
    },
    onUnlock: []
  },
  GreenRedEarly_08: {
    id: "GreenRedEarly_08",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "GreenRedEarly_08",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_09",
      "GreenRedEarly_Notable"
    ],
    uiPos: {
      x: 1705,
      y: 392
    },
    onUnlock: []
  },
  GreenRedEarly_09: {
    id: "GreenRedEarly_09",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "GreenRedEarly_09",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_08",
      "RedEarly_Notable_04"
    ],
    uiPos: {
      x: 1886,
      y: 270
    },
    onUnlock: []
  },
  GreenRedEarly_Notable: {
    id: "GreenRedEarly_Notable",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "GreenRedEarly_Notable",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Hybrid",
      "Notable",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_03",
      "GreenRedEarly_04",
      "GreenRedEarly_06",
      "GreenRedEarly_08"
    ],
    uiPos: {
      x: 1714,
      y: 530
    },
    onUnlock: []
  },
  GreenRedMid_Notable: {
    id: "GreenRedMid_Notable",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "GreenRedMidNotable_01",
    desc: "Bridge anchor (preserve domain).",
    cost: 2,
    tags: [
      "Green",
      "Hybrid",
      "Mid",
      "Notable",
      "Red"
    ],
    adjacent: [
      "GreenMid_06",
      "GreenRedEarly_05",
      "RedMid_06"
    ],
    uiPos: {
      x: 2315,
      y: 530
    },
    onUnlock: []
  },
  Hearth: {
    id: "Hearth",
    treeId: "systemColorMap",
    name: "RedEarly_Notable_01",
    desc: "",
    cost: 1,
    tags: [
      "Notable"
    ],
    adjacent: [
      "Cooking",
      "Forage",
      "Housing",
      "Memory"
    ],
    uiPos: {
      x: 784,
      y: 535
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "hubStructure",
        hubStructureId: "hearth"
      }
    ]
  },
  Housing: {
    id: "Housing",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "MudHouses_01",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Hybrid",
      "Notable",
      "Red"
    ],
    adjacent: [
      "Fish",
      "Hearth",
      "Worship"
    ],
    uiPos: {
      x: 724,
      y: 369
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "hubStructure",
        hubStructureId: "mudHouses"
      },
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "hub",
        tagId: "canHouse"
      },
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "hub",
        tagId: "canRest"
      }
    ]
  },
  Memory: {
    id: "Memory",
    treeId: "systemColorMap",
    name: "Memory",
    desc: "",
    cost: 1,
    tags: [
      "Notable"
    ],
    adjacent: [
      "Hearth"
    ],
    uiPos: {
      x: 680,
      y: 536
    },
    onUnlock: []
  },
  Papyrus: {
    id: "Papyrus",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "BlueNodeEarlyNotable_01",
    desc: "Cluster punctuation.",
    cost: 2,
    tags: [
      "Blue",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlackBlueEarly_01",
      "BlueEarly_02",
      "BlueEarly_04",
      "BlueEarly_05",
      "BlueEarly_08",
      "BlueGreenEarly_01"
    ],
    uiPos: {
      x: 364,
      y: 885
    },
    onUnlock: []
  },
  Preserve: {
    id: "Preserve",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "GreenEarly_Notable2",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Green",
      "Notable"
    ],
    adjacent: [
      "GreenEarly_06",
      "GreenEarly_08",
      "GreenEarly_09",
      "GreenEarly_11",
      "GreenMid_01"
    ],
    uiPos: {
      x: 1435,
      y: 1223
    },
    onUnlock: []
  },
  Prophecy: {
    id: "Prophecy",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlueEarlyNotable2",
    desc: "",
    cost: 1,
    tags: [
      "Blue",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlueEarly_06",
      "BlueEarly_07",
      "BlueEarly_09",
      "BlueEarly_11",
      "BlueMid_01"
    ],
    uiPos: {
      x: 33,
      y: 1261
    },
    onUnlock: []
  },
  RedBlackEarly_01: {
    id: "RedBlackEarly_01",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "RedBlackEarly_01",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Hybrid",
      "Red"
    ],
    adjacent: [
      "BlackEarly_Notable",
      "RedBlackEarly_03"
    ],
    uiPos: {
      x: 606,
      y: 41
    },
    onUnlock: []
  },
  RedBlackEarly_02: {
    id: "RedBlackEarly_02",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "RedBlackEarly_02",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Hybrid",
      "Red"
    ],
    adjacent: [
      "Distribute",
      "RedBlackEarly_03"
    ],
    uiPos: {
      x: 823,
      y: 41
    },
    onUnlock: []
  },
  RedBlackEarly_03: {
    id: "RedBlackEarly_03",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "RedBlackEarly_03",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Hybrid",
      "Red"
    ],
    adjacent: [
      "RedBlackEarly_01",
      "RedBlackEarly_02",
      "RedBlackEarly_Notable"
    ],
    uiPos: {
      x: 715,
      y: -270
    },
    onUnlock: []
  },
  RedBlackEarly_04: {
    id: "RedBlackEarly_04",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "RedBlackEarly_04",
    desc: "Hybrid bridge.",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Hybrid",
      "Red"
    ],
    adjacent: [
      "RedBlackEarly_05",
      "RedBlackEarly_Notable"
    ],
    uiPos: {
      x: 714,
      y: -670
    },
    onUnlock: []
  },
  RedBlackEarly_05: {
    id: "RedBlackEarly_05",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "RedBlackEarly_05",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Red"
    ],
    adjacent: [
      "RedBlackEarly_04",
      "RedBlackMid_Notable"
    ],
    uiPos: {
      x: 709,
      y: -970
    },
    onUnlock: []
  },
  RedBlackEarly_06: {
    id: "RedBlackEarly_06",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "RedBlackEarly_06",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Red"
    ],
    adjacent: [
      "RedBlackEarly_07",
      "RedBlackEarly_Notable"
    ],
    uiPos: {
      x: 852,
      y: -461
    },
    onUnlock: []
  },
  RedBlackEarly_07: {
    id: "RedBlackEarly_07",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "RedBlackEarly_07",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Red"
    ],
    adjacent: [
      "RedBlackEarly_06",
      "RedEarly_Notable_03"
    ],
    uiPos: {
      x: 974,
      y: -642
    },
    onUnlock: []
  },
  RedBlackEarly_08: {
    id: "RedBlackEarly_08",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "RedBlackEarly_08",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Red"
    ],
    adjacent: [
      "RedBlackEarly_09",
      "RedBlackEarly_Notable"
    ],
    uiPos: {
      x: 577,
      y: -461
    },
    onUnlock: []
  },
  RedBlackEarly_09: {
    id: "RedBlackEarly_09",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "RedBlackEarly_09",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Red"
    ],
    adjacent: [
      "BlackEarly_Notable_03",
      "RedBlackEarly_08"
    ],
    uiPos: {
      x: 455,
      y: -642
    },
    onUnlock: []
  },
  RedBlackEarly_Notable: {
    id: "RedBlackEarly_Notable",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "RedBlackEarly_Notable",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Hybrid",
      "Notable",
      "Red"
    ],
    adjacent: [
      "RedBlackEarly_03",
      "RedBlackEarly_04",
      "RedBlackEarly_06",
      "RedBlackEarly_08"
    ],
    uiPos: {
      x: 714,
      y: -470
    },
    onUnlock: []
  },
  RedBlackMid_Notable: {
    id: "RedBlackMid_Notable",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "RedBlackMidNotable_01",
    desc: "Bridge anchor (immediate domain).",
    cost: 2,
    tags: [
      "Black",
      "Hybrid",
      "Mid",
      "Notable",
      "Red"
    ],
    adjacent: [
      "BlackMid_06",
      "RedBlackEarly_05",
      "RedMid_04"
    ],
    uiPos: {
      x: 705,
      y: -1070
    },
    onUnlock: []
  },
  RedEarly_01: {
    id: "RedEarly_01",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "RedNodeEarly_01",
    desc: "Early ring.",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "Fish",
      "RedEarly_02"
    ],
    uiPos: {
      x: 860,
      y: 267
    },
    onUnlock: []
  },
  RedEarly_02: {
    id: "RedEarly_02",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "RedNodeEarly_02",
    desc: "Early ring.",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "Distribute",
      "RedEarly_01"
    ],
    uiPos: {
      x: 894,
      y: 288
    },
    onUnlock: []
  },
  RedEarly_03: {
    id: "RedEarly_03",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "RedNodeEarly_03",
    desc: "Early ring.",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "Fish",
      "RedEarly_04"
    ],
    uiPos: {
      x: 975,
      y: 391
    },
    onUnlock: []
  },
  RedEarly_04: {
    id: "RedEarly_04",
    ringId: "ring_01",
    treeId: "systemColorMap",
    name: "RedNodeEarly_04",
    desc: "Early ring.",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "Distribute",
      "RedEarly_03"
    ],
    uiPos: {
      x: 1003,
      y: 429
    },
    onUnlock: []
  },
  RedEarly_05: {
    id: "RedEarly_05",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "RedNodeEarly_05",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "Distribute",
      "RedEarly_06"
    ],
    uiPos: {
      x: 1183,
      y: -119
    },
    onUnlock: []
  },
  RedEarly_06: {
    id: "RedEarly_06",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "RedNodeEarly_06",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "RedEarly_05",
      "RedEarly_Notable_02"
    ],
    uiPos: {
      x: 988,
      y: -222
    },
    onUnlock: []
  },
  RedEarly_07: {
    id: "RedEarly_07",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "RedNodeEarly_07",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "Distribute",
      "RedEarly_08"
    ],
    uiPos: {
      x: 1466,
      y: 256
    },
    onUnlock: []
  },
  RedEarly_08: {
    id: "RedEarly_08",
    ringId: "ring_03",
    treeId: "systemColorMap",
    name: "RedNodeEarly_08",
    desc: "Early ring cluster B.",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "RedEarly_07",
      "RedEarly_Notable_02"
    ],
    uiPos: {
      x: 1363,
      y: 61
    },
    onUnlock: []
  },
  RedEarly_09: {
    id: "RedEarly_09",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "RedEarly_09",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "RedEarly_10",
      "RedEarly_Notable_03"
    ],
    uiPos: {
      x: 1231,
      y: -553
    },
    onUnlock: []
  },
  RedEarly_10: {
    id: "RedEarly_10",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "RedEarly_10",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "RedEarly_09",
      "RedEarly_Notable_02"
    ],
    uiPos: {
      x: 1379,
      y: -470
    },
    onUnlock: []
  },
  RedEarly_11: {
    id: "RedEarly_11",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "RedEarly_11",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "RedEarly_12",
      "RedEarly_Notable_02"
    ],
    uiPos: {
      x: 1696,
      y: -161
    },
    onUnlock: []
  },
  RedEarly_12: {
    id: "RedEarly_12",
    ringId: "ring_05",
    treeId: "systemColorMap",
    name: "RedEarly_12",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Red"
    ],
    adjacent: [
      "RedEarly_11",
      "RedEarly_Notable_04"
    ],
    uiPos: {
      x: 1795,
      y: 8
    },
    onUnlock: []
  },
  RedEarly_Notable_02: {
    id: "RedEarly_Notable_02",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "RedEarly_Notable_02",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Notable",
      "Red"
    ],
    adjacent: [
      "RedEarly_06",
      "RedEarly_08",
      "RedEarly_10",
      "RedEarly_11",
      "RedMid_01"
    ],
    uiPos: {
      x: 1388,
      y: -210
    },
    onUnlock: []
  },
  RedEarly_Notable_03: {
    id: "RedEarly_Notable_03",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "RedEarly_Notable_03",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Notable",
      "Red"
    ],
    adjacent: [
      "RedBlackEarly_07",
      "RedEarly_09"
    ],
    uiPos: {
      x: 1057,
      y: -410
    },
    onUnlock: []
  },
  RedEarly_Notable_04: {
    id: "RedEarly_Notable_04",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "RedEarly_Notable_04",
    desc: "",
    cost: 1,
    tags: [
      "Early",
      "Notable",
      "Red"
    ],
    adjacent: [
      "GreenRedEarly_09",
      "RedEarly_12"
    ],
    uiPos: {
      x: 1654,
      y: 187
    },
    onUnlock: []
  },
  RedLate_01: {
    id: "RedLate_01",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "RedNodeLate_01",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Late",
      "Red"
    ],
    adjacent: [
      "RedLate_02",
      "RedMid_Notable"
    ],
    uiPos: {
      x: 1819,
      y: -892
    },
    onUnlock: []
  },
  RedLate_02: {
    id: "RedLate_02",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "RedNodeLate_02",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Late",
      "Red"
    ],
    adjacent: [
      "RedLate_01",
      "RedLate_03"
    ],
    uiPos: {
      x: 1893,
      y: -831
    },
    onUnlock: []
  },
  RedLate_03: {
    id: "RedLate_03",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "RedNodeLate_03",
    desc: "Late ring.",
    cost: 3,
    tags: [
      "Late",
      "Red"
    ],
    adjacent: [
      "RedLate_02",
      "RedLate_Notable"
    ],
    uiPos: {
      x: 2096,
      y: -624
    },
    onUnlock: []
  },
  RedLate_Notable: {
    id: "RedLate_Notable",
    ringId: "ring_09",
    treeId: "systemColorMap",
    name: "RedNodeLateNotable_01",
    desc: "Outer edge anchor.",
    cost: 4,
    tags: [
      "Late",
      "Notable",
      "Red"
    ],
    adjacent: [
      "RedLate_03"
    ],
    uiPos: {
      x: 2190,
      y: -501
    },
    onUnlock: []
  },
  RedMid_01: {
    id: "RedMid_01",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "RedNodeMid_01",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Mid",
      "Red"
    ],
    adjacent: [
      "RedEarly_Notable_02",
      "RedMid_02"
    ],
    uiPos: {
      x: 1717,
      y: -586
    },
    onUnlock: []
  },
  RedMid_02: {
    id: "RedMid_02",
    ringId: "ring_06",
    treeId: "systemColorMap",
    name: "RedNodeMid_02",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Mid",
      "Red"
    ],
    adjacent: [
      "RedMid_01",
      "RedMid_Notable"
    ],
    uiPos: {
      x: 1809,
      y: -496
    },
    onUnlock: []
  },
  RedMid_03: {
    id: "RedMid_03",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "RedNodeMid_03",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Mid",
      "Red"
    ],
    adjacent: [
      "RedMid_04",
      "RedMid_Notable"
    ],
    uiPos: {
      x: 1631,
      y: -902
    },
    onUnlock: []
  },
  RedMid_04: {
    id: "RedMid_04",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "RedNodeMid_04",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Mid",
      "Red"
    ],
    adjacent: [
      "RedBlackMid_Notable",
      "RedMid_03"
    ],
    uiPos: {
      x: 1296,
      y: -1068
    },
    onUnlock: []
  },
  RedMid_05: {
    id: "RedMid_05",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "RedNodeMid_05",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Mid",
      "Red"
    ],
    adjacent: [
      "RedMid_06",
      "RedMid_Notable"
    ],
    uiPos: {
      x: 2141,
      y: -395
    },
    onUnlock: []
  },
  RedMid_06: {
    id: "RedMid_06",
    ringId: "ring_08",
    treeId: "systemColorMap",
    name: "RedNodeMid_06",
    desc: "Mid ring.",
    cost: 2,
    tags: [
      "Mid",
      "Red"
    ],
    adjacent: [
      "GreenRedMid_Notable",
      "RedMid_05"
    ],
    uiPos: {
      x: 2312,
      y: -52
    },
    onUnlock: []
  },
  RedMid_Notable: {
    id: "RedMid_Notable",
    ringId: "ring_07",
    treeId: "systemColorMap",
    name: "RedNodeMidNotable_01",
    desc: "Mid anchor.",
    cost: 2,
    tags: [
      "Mid",
      "Notable",
      "Red"
    ],
    adjacent: [
      "RedLate_01",
      "RedMid_02",
      "RedMid_03",
      "RedMid_05"
    ],
    uiPos: {
      x: 1828,
      y: -620
    },
    onUnlock: []
  },
  Storehouse: {
    id: "Storehouse",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "Granary",
    desc: "Cluster punctuation.",
    cost: 2,
    tags: [
      "Early",
      "Green",
      "Notable"
    ],
    adjacent: [
      "BlueGreenEarly_02",
      "GreenEarly_02",
      "GreenEarly_04",
      "GreenEarly_05",
      "GreenEarly_07",
      "GreenRedEarly_02"
    ],
    uiPos: {
      x: 998,
      y: 942
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "hubStructure",
        hubStructureId: "storehouse"
      }
    ]
  },
  Weaving: {
    id: "Weaving",
    ringId: "ring_04",
    treeId: "systemColorMap",
    name: "BlackBlueEarly_Notable_01",
    desc: "",
    cost: 2,
    tags: [
      "Black",
      "Blue",
      "Early",
      "Hybrid",
      "Notable"
    ],
    adjacent: [
      "BlackEarly_01",
      "BlueEarly_04"
    ],
    uiPos: {
      x: 288,
      y: 519
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "recipe",
        recipeId: "weaveBasket"
      }
    ]
  },
  Worship: {
    id: "Worship",
    ringId: "ring_02",
    treeId: "systemColorMap",
    name: "BlackEarly_Notable_01",
    desc: "",
    cost: 1,
    tags: [
      "Black",
      "Early",
      "Notable"
    ],
    adjacent: [
      "BlackEarly_02",
      "BlackEarly_03",
      "Crafting",
      "Housing"
    ],
    uiPos: {
      x: 637,
      y: 447
    },
    onUnlock: [
      {
        op: "GrantUnlock",
        unlockType: "hubStructure",
        hubStructureId: "ritualShrine"
      },
      {
        op: "GrantUnlock",
        unlockType: "tag",
        tagDomain: "hub",
        tagId: "depositable"
      }
    ]
  }
};
