export const keywordDefs = {
  follower: {
    id: "follower",
    label: "Follower",
    accentColor: 0x7ae2d9,
    group: "pawn",
    description: "A worker who spends stamina on local tasks.",
  },
  faith: {
    id: "faith",
    label: "Faith",
    accentColor: 0x7ec3ff,
    group: "pawn",
    description: "Leader stability. Starvation can drive it down.",
  },
  stamina: {
    id: "stamina",
    label: "Stamina",
    accentColor: 0xc88b4d,
    group: "pawn",
    description: "Work energy. Rest restores it.",
  },
  hunger: {
    id: "hunger",
    label: "Hunger",
    accentColor: 0xd65f4a,
    group: "pawn",
    description: "Food pressure. Low hunger forces food-seeking behavior.",
  },
  seek: {
    id: "seek",
    label: "Seek",
    accentColor: 0xf0d176,
    group: "behavior",
    description: "The pawn moves toward a need-satisfying location.",
  },
  rest: {
    id: "rest",
    label: "Rest",
    accentColor: 0xcdb07b,
    group: "behavior",
    description: "Recover stamina at a valid rest spot.",
  },
  starving: {
    id: "starving",
    label: "Starving",
    accentColor: 0xf06f5f,
    group: "behavior",
    description: "Critical hunger state.",
  },
  edible: {
    id: "edible",
    label: "Edible",
    accentColor: 0x8fd081,
    group: "item",
    description: "Can be eaten.",
  },
  perishable: {
    id: "perishable",
    label: "Perishable",
    accentColor: 0xd1b26f,
    group: "item",
    description: "Can rot over time.",
  },
  deposit: {
    id: "deposit",
    label: "Deposit",
    accentColor: 0x7ec3ff,
    group: "hub",
    description: "Moves items into a storage pool.",
  },
  prestige: {
    id: "prestige",
    label: "Prestige",
    accentColor: 0xe4d27f,
    group: "hub",
    description: "Leadership capacity that funds followers and workers.",
  },
};
