// src/model/graph-metrics.js
// Metric definitions for time graphs.

import { YOUTH_PER_FOOD } from "../defs/gamesettings/gamerules-defs.js";
import { getTotalFoodFromEdibles, getTotalStackByTag } from "./query.js";
import {
  getSettlementFaithGraphValue,
  getSettlementFaithSummary,
  getSettlementHappinessGraphValue,
  getSettlementHappinessSummary,
  getSettlementFloodplainTiles,
  getSettlementPopulationSummary,
  getSettlementStockpile,
  isSettlementPrototypeEnabled,
} from "./settlement-state.js";

function capitalizeLabel(value) {
  const text = typeof value === "string" ? value : "";
  if (!text.length) return "None";
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function getSettlementFoodTooltipSpec(state) {
  const population = getSettlementPopulationSummary(state);
  const food = getSettlementStockpile(state, "food");
  const foodCapacity = Math.max(0, Math.floor(state?.hub?.core?.props?.foodCapacity ?? 0));
  const youthPerFood = Number.isFinite(YOUTH_PER_FOOD) ? Math.max(1, Math.floor(YOUTH_PER_FOOD)) : 2;
  const weightedDemand = population.adults + Math.ceil(population.youth / youthPerFood);
  return {
    title: "Food",
    lines: [
      `Current stockpile: ${Math.floor(food)}/${foodCapacity}`,
      `Each season change consumes up to ${weightedDemand} food (${population.adults} adults + ${population.youth} youth, with 1 food per ${youthPerFood} youth and odd youth rounded up).`,
      "Spring rollovers resolve the last year's population and faith before the new season meal.",
    ],
  };
}

function getSettlementRedTooltipSpec(state) {
  const population = getSettlementPopulationSummary(state);
  const red = getSettlementStockpile(state, "redResource");
  const redCap = Math.max(0, population.total);
  return {
    title: "Red Resource",
    lines: [
      `Current stockpile: ${Math.floor(red)}/${redCap}`,
      "Generated by Flood Rites and capped by total population.",
    ],
  };
}

function getSettlementGreenTooltipSpec(state) {
  const green = getSettlementStockpile(state, "greenResource");
  const floodplains = getSettlementFloodplainTiles(state).length;
  return {
    title: "Green Resource",
    lines: [
      `Current stockpile: ${Math.floor(green)}`,
      `Stored on ${floodplains} floodplain tile${floodplains === 1 ? "" : "s"}.`,
      "Autumn floods clear stored green from the floodplains.",
    ],
  };
}

function formatClassLabel(classId) {
  return capitalizeLabel(typeof classId === "string" ? classId : "villager");
}

function getSettlementPopulationTooltipSpec(state, classId = null) {
  const population = getSettlementPopulationSummary(state, classId);
  return {
    title: `${classId ? `${formatClassLabel(classId)} ` : ""}Population`,
    lines: [
      `Total population: ${population.total}`,
      `Adults: ${population.adults}`,
      `Youth: ${population.youth}`,
      `Reserved by structures/practices: ${population.reserved}`,
      `Free population: ${population.free}`,
    ],
  };
}

function getSettlementFreePopulationTooltipSpec(state, classId = null) {
  const population = getSettlementPopulationSummary(state, classId);
  return {
    title: `${classId ? `${formatClassLabel(classId)} ` : ""}Free Population`,
    lines: [
      `Free population: ${population.free}`,
      `Structure staffing: ${population.staffed}`,
      `Practice commitments: ${population.committed}`,
    ],
  };
}

function getSettlementFaithTooltipSpec(state, classId = null) {
  const faith = getSettlementFaithSummary(state, classId);
  const happiness = getSettlementHappinessSummary(state, classId);
  return {
    title: `${classId ? `${formatClassLabel(classId)} ` : ""}Faith`,
    lines: [
      `Current tier: ${capitalizeLabel(faith.tier)}`,
      `Current happiness: ${capitalizeLabel(happiness.status)}`,
      "At each spring rollover, positive happiness raises faith and negative happiness lowers it.",
    ],
  };
}

function getSettlementHappinessTooltipSpec(state, classId = null) {
  const happiness = getSettlementHappinessSummary(state, classId);
  const partialMemory =
    happiness.partialFeedRatios.length > 0
      ? happiness.partialFeedRatios.map((value) => `${Math.round(value * 100)}%`).join(" -> ")
      : "None";
  return {
    title: `${classId ? `${formatClassLabel(classId)} ` : ""}Happiness`,
    lines: [
      `Current state: ${capitalizeLabel(happiness.status)}`,
      `Full-feed streak: ${happiness.fullFeedStreak}/${happiness.fullFeedThreshold}`,
      `Missed-feed streak: ${happiness.missedFeedStreak}/${happiness.missedFeedThreshold}`,
      `Partial memory: ${partialMemory}`,
      "Three full seasons set happiness to positive. Three consecutive misses trigger starvation, and further misses keep triggering it until the class gets at least a 50% feed. Partial ratios improve on 3 rising steps and worsen immediately on flat-or-lower steps.",
    ],
  };
}

export const GRAPH_METRICS = {
  gold: {
    id: "gold",
    label: "Gold",
    series: [
      {
        id: "gold",
        label: "Gold",
        color: 0xffd966,
        getValue: (state, _subject) => state?.resources?.gold ?? state?.gold ?? 0,
        getValueFromSnapshot: (snapshot, _subject) =>
          snapshot?.resources?.gold ?? snapshot?.gold ?? 0,
        formatValue: (value) =>
          Number.isFinite(value) ? value.toFixed(1) : "0.0",
      },
    ],
  },
  grain: {
    id: "grain",
    label: "Grain",
    series: [
      {
        id: "grain",
        label: "Grain",
        color: 0xd3b562,
        getValue: (state, _subject) => getTotalStackByTag(state, "grain"),
        getValueFromSnapshot: (snapshot, _subject) =>
          getTotalStackByTag(snapshot, "grain"),
        formatValue: (value) =>
          Number.isFinite(value) ? value.toFixed(1) : "0.0",
      },
    ],
  },
  food: {
    id: "food",
    label: "Food",
    series: [
      {
        id: "food",
        label: "Food",
        color: 0x66cc77,
        getValue: (state, _subject) => {
          if (isSettlementPrototypeEnabled(state)) {
            return getSettlementStockpile(state, "food");
          }
          const base = state?.resources?.food ?? 0;
          const edible = getTotalFoodFromEdibles(state);
          const baseSafe = Number.isFinite(base) ? base : 0;
          const edibleSafe = Number.isFinite(edible) ? edible : 0;
          return baseSafe + edibleSafe;
        },
        getValueFromSnapshot: (snapshot, _subject) => {
          if (isSettlementPrototypeEnabled(snapshot)) {
            return getSettlementStockpile(snapshot, "food");
          }
          const base = snapshot?.resources?.food ?? 0;
          const edible = getTotalFoodFromEdibles(snapshot);
          const baseSafe = Number.isFinite(base) ? base : 0;
          const edibleSafe = Number.isFinite(edible) ? edible : 0;
          return baseSafe + edibleSafe;
        },
        formatValue: (value) =>
          Number.isFinite(value) ? value.toFixed(1) : "0.0",
      },
    ],
  },
  ap: {
    id: "ap",
    label: "AP",
    series: [
      {
        id: "apCap",
        label: "AP Cap",
        color: 0xffaa66,
        getValue: (state, _subject) => state?.actionPointCap ?? 0,
        getValueFromSnapshot: (snapshot, _subject) =>
          snapshot?.actionPointCap ?? 0,
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
      {
        id: "ap",
        label: "AP",
        color: 0x66ccff,
        getValue: (state, _subject) => state?.actionPoints ?? 0,
        getValueFromSnapshot: (snapshot, _subject) =>
          snapshot?.actionPoints ?? 0,
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
    ],
  },
  population: {
    id: "population",
    label: "Population",
    series: [
      {
        id: "population",
        label: "Population",
        color: 0xb8a4ff,
        getValue: (state, _subject) =>
          isSettlementPrototypeEnabled(state)
            ? getSettlementPopulationSummary(state).total
            : state?.resources?.population ?? state?.population ?? 0,
        getValueFromSnapshot: (snapshot, _subject) =>
          isSettlementPrototypeEnabled(snapshot)
            ? getSettlementPopulationSummary(snapshot).total
            : snapshot?.resources?.population ?? snapshot?.population ?? 0,
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
    ],
  },
  settlement: {
    id: "settlement",
    label: "Settlement",
    getLabel: (subject) =>
      subject?.classId ? `Settlement - ${formatClassLabel(subject.classId)}` : "Settlement",
    getSubjectKey: (subject) => subject?.classId ?? null,
    series: [
      {
        id: "food",
        label: "Food",
        color: 0xdcc56f,
        getValue: (state) => getSettlementStockpile(state, "food"),
        getValueFromSnapshot: (snapshot) => getSettlementStockpile(snapshot, "food"),
        getLegendTooltipSpec: (state) => getSettlementFoodTooltipSpec(state),
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
      {
        id: "redResource",
        label: "Red",
        color: 0xc55c4a,
        getValue: (state) => getSettlementStockpile(state, "redResource"),
        getValueFromSnapshot: (snapshot) => getSettlementStockpile(snapshot, "redResource"),
        getLegendTooltipSpec: (state) => getSettlementRedTooltipSpec(state),
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
      {
        id: "greenResource",
        label: "Green",
        color: 0x7eb37d,
        getValue: (state) => getSettlementStockpile(state, "greenResource"),
        getValueFromSnapshot: (snapshot) => getSettlementStockpile(snapshot, "greenResource"),
        getLegendTooltipSpec: (state) => getSettlementGreenTooltipSpec(state),
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
      {
        id: "totalPopulation",
        label: "Pop",
        color: 0xb8a4ff,
        getValue: (state, subject) =>
          getSettlementPopulationSummary(state, subject?.classId ?? null).total,
        getValueFromSnapshot: (snapshot, subject) =>
          getSettlementPopulationSummary(snapshot, subject?.classId ?? null).total,
        getLegendTooltipSpec: (state, subject) =>
          getSettlementPopulationTooltipSpec(state, subject?.classId ?? null),
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
      {
        id: "freePopulation",
        label: "Free",
        color: 0x8ec3f2,
        getValue: (state, subject) =>
          getSettlementPopulationSummary(state, subject?.classId ?? null).free,
        getValueFromSnapshot: (snapshot, subject) =>
          getSettlementPopulationSummary(snapshot, subject?.classId ?? null).free,
        getLegendTooltipSpec: (state, subject) =>
          getSettlementFreePopulationTooltipSpec(state, subject?.classId ?? null),
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
      {
        id: "faith",
        label: "Faith",
        color: 0xf1de7a,
        getValue: (state, subject) => getSettlementFaithGraphValue(state, subject?.classId ?? null),
        getValueFromSnapshot: (snapshot, subject) =>
          getSettlementFaithGraphValue(snapshot, subject?.classId ?? null),
        getLegendTooltipSpec: (state, subject) =>
          getSettlementFaithTooltipSpec(state, subject?.classId ?? null),
        formatValue: (value) =>
          Number.isFinite(value) ? `${Math.floor(value)}` : "0",
      },
      {
        id: "happiness",
        label: "Happy",
        color: 0xf2a766,
        getValue: (state, subject) =>
          getSettlementHappinessGraphValue(state, subject?.classId ?? null),
        getValueFromSnapshot: (snapshot, subject) =>
          getSettlementHappinessGraphValue(snapshot, subject?.classId ?? null),
        getLegendTooltipSpec: (state, subject) =>
          getSettlementHappinessTooltipSpec(state, subject?.classId ?? null),
        formatValue: (value) =>
          value >= 75 ? "Positive" : value <= 25 ? "Negative" : "Neutral",
      },
    ],
  },
};

function mergeSeries(metrics) {
  const merged = [];
  const seen = new Set();
  for (const metric of metrics) {
    const series = Array.isArray(metric?.series) ? metric.series : [];
    for (const s of series) {
      if (!s || !s.id || seen.has(s.id)) continue;
      merged.push(s);
      seen.add(s.id);
    }
  }
  return merged;
}

GRAPH_METRICS.all = {
  id: "all",
  label: "All",
  series: mergeSeries([
    GRAPH_METRICS.gold,
    GRAPH_METRICS.grain,
    GRAPH_METRICS.food,
    GRAPH_METRICS.ap,
    GRAPH_METRICS.population,
    GRAPH_METRICS.settlement,
  ]),
};

export function getGraphMetric(metricId) {
  return GRAPH_METRICS[metricId] || GRAPH_METRICS.gold;
}
