import assert from 'node:assert/strict';
import {getDetailedSettlement,getElderMortalityRate,resolveProbability,stepDetailedSettlementsSecond} from '../../detailed-settlements.js';
import {serializeGameState,deserializeGameState} from '../../state.js';
import {getMoonPhaseAtSecond} from '../../moon-phases.js';
import {getPopulationSummary} from '../../detailed-settlements/queries.js';
import {specialistCount,trainSpecialists,stockTotal} from '../../detailed-settlements/stock.js';
import {selectPopulationComposition,compositionTotal} from '../../detailed-settlements/helpers.js';
import {removePopulationComposition,addCompositionToStrangers} from '../../detailed-settlements/phases/migration.js';
import {validSpecialistCohorts} from '../../detailed-settlements/cohorts.js';
import {fresh,clearDetailedPopulationAndFood,disableMonthlyDemographics} from './helpers.js';
const slot=(id,stock)=>({practiceId:id,stock,tier:'bronze',charge:0,work:0});
const fixture=()=>{
 const state=disableMonthlyDemographics(clearDetailedPopulationAndFood(fresh(880)));
 state.gameConfig.settings.values.primordialBasePressure=0;
 // Isolate meals from production, retaining the authoritative hosted inventory.
 state.gameConfig.gamepieces.practices.forage.effects[0].amount=0;
 return state;
};
assert.deepEqual([49,50,55,60,65,70,75].map(getElderMortalityRate),[.0025,.005,.015,.04,.08,.16,.3]);
assert.equal(resolveProbability(.2,{additive:[.2],multipliers:[2]}),.8);
assert.equal(resolveProbability(.8,{additive:[.4],multipliers:[2]}),1);
for(const [population,stock,expected] of [[1,1,1],[30,1,1],[31,1,.5],[60,1,.5],[61,1,1/3]]) {
 const state=fixture(),settlement=getDetailedSettlement(state,'cedar-woods');
 settlement.populationByClass.villager.adults=population;
 settlement.practiceSlots[0]=slot('forage',stock);
 stepDetailedSettlementsSecond(state,1);stepDetailedSettlementsSecond(state,2);
 assert.equal(settlement.lastMeal.demand,Math.ceil(population/30));
 assert.ok(Math.abs(settlement.lastMeal.ratio-expected)<.0001);
 assert.equal(stockTotal(state,settlement,'Edible'),0);
}
const rationed=fixture(),r=getDetailedSettlement(rationed,'cedar-woods');
r.populationByClass.villager.adults=60;r.practiceSlots=[slot('forage',1),slot('rationing'),...Array(10).fill(null)];
stepDetailedSettlementsSecond(rationed,1);stepDetailedSettlementsSecond(rationed,2);
assert.equal(r.lastMeal.ratio,1,'one saved Stock band feeds 30 people');
assert.equal(stockTotal(rationed,r,'Edible'),0);
const priority=fixture(),p=getDetailedSettlement(priority,'cedar-woods');
p.populationByClass.villager.adults=20;p.populationByClass.stranger.adults=20;p.practiceSlots[0]=slot('forage',1);
stepDetailedSettlementsSecond(priority,1);stepDetailedSettlementsSecond(priority,2);
assert.equal(p.lastMeal.byClass.villager.ratio,1);assert.equal(p.lastMeal.byClass.stranger.ratio,.5);
const hunger=fixture(),h=getDetailedSettlement(hunger,'cedar-woods');h.populationByClass.villager.adults=20;
for(let sec=1;sec<=14;sec++)stepDetailedSettlementsSecond(hunger,sec);
assert.equal(h.lastMeal.byClass.villager.migrants,20,'three missed meals reserve unfed population');
assert.equal(h.lastMeal.byClass.villager.targetHappiness,'negative');
const migration=fixture(),source=getDetailedSettlement(migration,'cedar-woods'),destination=getDetailedSettlement(migration,'west-levee');
source.populationByClass.villager.adults=20;trainSpecialists(source,'scholar',3);trainSpecialists(source,'warrior',7);
const composition=selectPopulationComposition(source,['villager'],20);assert.equal(compositionTotal(composition),20);
removePopulationComposition(source,composition);addCompositionToStrangers(destination,composition);
assert.equal(getPopulationSummary(migration,'cedar-woods').total,0);assert.equal(destination.populationByClass.stranger.adults,20);
assert.equal(specialistCount(destination,'scholar'),3);assert.equal(specialistCount(destination,'warrior'),7);
assert.equal(validSpecialistCohorts(destination.populationByClass.stranger),true);
const aging=fixture(),a=getDetailedSettlement(aging,'cedar-woods');a.populationByClass.villager.adults=10;trainSpecialists(a,'warrior',10);
aging.gameConfig.settings.values.adultToElderRate=1;stepDetailedSettlementsSecond(aging,1);
assert.equal(specialistCount(a,'warrior'),10);assert.equal(a.populationByClass.villager.specialists.warrior.adults,0);
assert.equal(validSpecialistCohorts(a.populationByClass.villager),true);
const death=fixture(),d=getDetailedSettlement(death,'cedar-woods');d.populationByClass.villager.eldersByAge=[{age:75,count:3}];
d.populationByClass.villager.specialists.scholar.eldersByAge=[{age:75,count:2}];death.gameConfig.settings.values.elderMortality75Plus=1;
stepDetailedSettlementsSecond(death,1);stepDetailedSettlementsSecond(death,6);
assert.equal(d.populationByClass.villager.eldersByAge.length,0);assert.equal(specialistCount(d,'scholar'),0);
const slower=fresh();slower.gameConfig.settings.values.phaseDurationSec=2;
assert.deepEqual([1,2,3,5,7,9,11,13].map(sec=>{const p=getMoonPhaseAtSecond(slower,sec);return `${p.id}:${p.boundary}`;}),['birth:true','birth:false','food:true','housing:true','faith:true','migration:true','death:true','birth:true']);
const mid=fixture();getDetailedSettlement(mid,'cedar-woods').populationByClass.villager.adults=12;
for(const sec of [1,2,3])stepDetailedSettlementsSecond(mid,sec);
const copy=deserializeGameState(serializeGameState(mid));
for(const sec of [4,5,6]){stepDetailedSettlementsSecond(mid,sec);stepDetailedSettlementsSecond(copy,sec);}
assert.deepEqual(serializeGameState(mid),serializeGameState(copy),'mid-moon reservations survive reload');
