import assert from 'node:assert/strict';
import { applyBuild, applyStructureUpgrade, findStructurePlacement, normalizeStructureLayout, occupiedCells, projectStructureDraft, validateStructureLayout } from '../structure-layout.js';
import { projectPracticeDraft } from '../practice-draft.js';

const strip = normalizeStructureLayout([{ structureId: 'house' }, null, { structureId: 'hall', width: 2 }], 8, () => ({ footprint: 1 }), 'test');
assert.equal(validateStructureLayout(strip).ok, true);
assert.deepEqual(occupiedCells(strip).map(p => p?.structureId ?? null), ['house', null, 'hall', 'hall', null, null, null, null]);
assert.equal(findStructurePlacement(strip, 3, { allowDemolition: true }).origin, 4, 'free span wins over earlier demolition');
const build = { placementId: 'incoming', origin: 1, width: 3, structureId: 'university', tier: 'gold' };
assert.equal(applyBuild(strip, build).ok, false, 'ordinary simulation builds cannot demolish');
const draft = projectStructureDraft(strip, [build]);
assert.equal(draft.ok, true);
assert.deepEqual(draft.demolished.map(p => p.structureId), ['hall']);
assert.deepEqual(strip[2].structureId, 'hall', 'staging never mutates confirmed state');
assert.deepEqual(projectStructureDraft(strip, []).slots, strip, 'undo restores covered buildings');
assert.equal(projectStructureDraft(strip, [build, { ...build, placementId: 'overlap', origin: 3, width: 1 }]).reason, 'stagedStructureOverlap');
assert.equal(projectStructureDraft(strip, [{ ...build, origin: 6 }]).reason, 'outsideConstructionStrip');
const full = normalizeStructureLayout(Array.from({length:5},()=>({structureId:'house'})),5,()=>({footprint:1}));
assert.equal(findStructurePlacement(full,2,{allowDemolition:true}).origin,0, 'full strip uses leftmost compatible demolition');
const upgrade = { mode: 'upgrade', targetPlacementId: strip[2].placementId, structureId: 'hall', previousTier: 'bronze', tier: 'silver', width: 2 };
const upgraded = projectStructureDraft(strip, [upgrade]);
assert.equal(upgraded.slots[2].placementId, strip[2].placementId);
assert.equal(upgraded.slots[2].width, 2);
assert.equal(upgraded.slots[2].tier, 'silver');
assert.equal(applyStructureUpgrade(strip, strip[2].placementId, {...upgrade,width:3}).ok,false);
assert.equal(projectStructureDraft(strip, [upgrade,{...build,origin:2}]).ok,false);
assert.deepEqual(projectStructureDraft(JSON.parse(JSON.stringify(strip)), JSON.parse(JSON.stringify([build]))), draft);
const confirmed = ['a','b','c','d','e'].map(practiceId => ({practiceId,tier:'bronze',charge:0,work:0}));
const purchases = [{intervention:{kind:'practice',mode:'learn',practiceId:'f',resultingTier:'bronze'}},{intervention:{kind:'practice',mode:'upgrade',practiceId:'e',tier:'bronze',resultingTier:'silver'}}];
assert.deepEqual(projectPracticeDraft(confirmed,purchases).slots.map(p=>p.practiceId),['f','e','a','b','c']);
assert.deepEqual(projectPracticeDraft(confirmed,[...purchases].reverse()).slots.map(p=>p.practiceId),['e','f','a','b','c']);
assert.deepEqual(projectPracticeDraft(confirmed,[]).slots,confirmed);
const sparse = [confirmed[0], null, confirmed[2], null, confirmed[4]];
assert.deepEqual(projectPracticeDraft(sparse,[]).slots,sparse,'An empty draft never compacts confirmed slots');
assert.deepEqual(projectPracticeDraft(sparse,[purchases[0]]).slots.map(p=>p?.practiceId??null),['f','a',null,'c',null],'Incoming practice preserves unshift displacement and surviving gaps');
assert.equal(validateStructureLayout([{placementId:'bad',origin:0,width:Infinity}]).ok,false,'Invalid widths are rejected without iterating their cells');
assert.throws(()=>normalizeStructureLayout([{structureId:'wide',width:3},{structureId:'overlap'}],5,()=>({footprint:1})),/Invalid authored construction/);
console.log('Structure layout and practice prefix tests passed.');
